<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('blacklist', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->timestamps();
            $table->softDeletes();
        });

        $blacklist =  [
            "bosta",
            "pica",
            "merda",
            "porra",
            "caralho",
            "cu",
            "puta",
            "piranha",
            "vagabunda",
            "desgraça",
            "fdp",
            "filho da puta",
            "arrombado",
            "viado",
            "corno",
            "cacete",
            "caceta",
            "escroto",
            "puta que pariu",
            "foda",
            "fodido",
            "imbecil",
            "burro",
            "idiota",
            "otário",
            "otaria",
            "paspalho",
            "panaca",
            "retardado",
            "merdinha",
            "cuzão",
            "cuzinha",
            "baitola",
            "boiola",
            "trouxa",
            "mané",
            "babaca",
            "chupeta",
            "chupetinha",
            "roludo",
            "rola",
            "pau no cu",
            "pau no seu cu",
            "nojento",
            "nojenta",
            "moleque",
            "delinquente",
            "delinquenta",
            "peste",
            "maldito",
            "maldita",
            "corna",
            "fedorento",
            "fedorenta",
            "nojento",
            "nojenta",
            "cabaço",
            "babacão",
            "tapado",
            "idiotice",
            "bocó",
            "cretino",
            "vagabundo",
            "lixo",
            "escória",
            "esgoto",
            "escrotidão",
            "trouxa",
            "cabeça de piroca",
            "mal caráter",
            "safado",
            "safada",
            "sem vergonha",
            "sem noção",
            "burra",
            "anta",
            "mula",
            "asno",
            "idiotão",
            "zé ruela",
            "zé mané",
            "abestado",
            "cabeçudo",
            "pentelho",
            "saco",
            "sacudo",
            "punheta",
            "punheteiro",
            "punheteira",
            "enfiar no cu",
            "chupa rola",
            "enrabado",
            "putinha",
            "cadela",
            "maluca",
            "doida",
            "trambiqueiro",
            "trambiqueira",
            "zé buceta",
            "buceta",
            "xana",
            "xoxota",
            "rabo",
            "rabeta",
            "suruba",
            "orgia",
            "pederasta",
            "escrotinho",
            "nojentão",
            "mijado",
            "peido",
            "peidorreiro",
            "xixi",
            "mijona",
            "pentelhudo",
            "escrotona",
            "chifrudo",
            "tarado",
            "tarada",
            "pedófilo",
            "pedófila",
            "estuprador",
            "estupradora",
            "maníaco",
            "pervertido",
            "pervertida",
            "bucetinha",
            "vaginet",
            "anal",
            "analzinho",
            "chupa",
            "lambe bola",
            "lambe saco",
            "gostosa",
            "gostosona",
            "gostoso",
            "pauzudo",
            "pintudo",
            "garganta profunda",
            "depilada",
            "tesuda",
            "sedenta",
            "safadeza",
            "tesão",
            "taradão",
            "luxúria",
            "seduzente",
            "pervertido",
            "molhadinha",
            "fodelança",
            "putaria",
            "boquete",
            "oral",
            "mamando",
            "foda-se",
            "vai se foder",
            "vai tomar no cu",
            "vai pra puta que pariu",
            "vai se lascar",
            "vai pro inferno",
            "vai cagar",
            "enfia no rabo",
            "shit",
            "fuck",
            "fucking",
            "bitch",
            "bastard",
            "asshole",
            "dick",
            "cunt",
            "pussy",
            "motherfucker",
            "son of a bitch",
            "damn",
            "jerk",
            "loser",
            "idiot",
            "moron",
            "retard",
            "dumbass",
            "nigger",
            "negro",
            "wetback",
            "beaner",
            "chink",
            "slut",
            "whore",
            "rapist",
            "pedophile",
            "molester",
            "perv",
            "sucker",
            "twat",
            "cock",
            "balls",
            "screw you",
            "get lost",
            "go to hell",
            "shithead",
            "piss off",
            "wanker",
            "bloody hell",
            "arsehole",
            "bollocks",
            "numbnuts",
            "douche",
            "douchebag",
            "cum",
            "splooge",
            "orgasm",
            "horny",
            "humping",
            "bang",
            "suck my dick",
            "lick my balls",
            "anal fuck",
            "deepthroat",
            "butt",
            "fuckwit",
            "prick",
            "cocksucker",
            "blowjob",
            "gangbang",
            "handjob",
            "rimjob",
            "spank",
            "kinky",
            "bdsm",
            "rape",
            "gagging",
            "groping",
            "incest",
            "creampie",
            "milf",
            "nude",
            "naked",
            "strip",
            "nipple",
            "boobs",
            "tits",
            "jugs",
            "fuckboy",
            "fuckgirl",
            "cumdumpster",
            "sexslave",
            "slave",
            "pee",
            "poop",
            "sperm",
            "ejaculate",
            "masturbate",
            "dildo",
            "vibrator",
            "penetration",
            "intercourse",
            "lube",
            "clit",
            "clitoris",
            "pubes",
            "erection",
            "hardon",
            "sex addict",
            "pervert",
            "porn",
            "porno",
            "xxx",
            "69",
            "doggy style",
            "reverse cowgirl",
            "butthole",
            "arse",
            "bugger",
            "manwhore",
            "skank",
            "ho",
            "hoe",
            "thot",
            "tramp",
            "fetish",
            "squirting",
            "bukkake",
            "moneyshot",
            "anal beads",
            "strapon",
            "gangbang",
            "hooker",
            "escort",
            "prostitute",
            "camgirl",
            "camwhore",
            "nudity",
            "explicit"
        ];

        for ($i = 0; $i < count($blacklist); $i++) {
            DB::table('blacklist')->insert([
                'name' => $blacklist[$i],
                'created_at' => now(),
            ]);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('blacklist');
    }
};